### ISSUE TITLE
Right-click is not handled

### ISSUE THREAD

**Issue by yuya-takeyama** [drikin/slk#7]
For now, slk is much better than official app in private beta.

But right-click seems not handled.
For example, I can't copy link of message permalinks.

**Comment by drikin** [comment]
Thank you for your feedback. Yeah, I'm also having many improving ideas but I think it's better to give feedbacks for official client. 

I also think keyboard shortcut is still working for copy and paste.

**Comment by yuya-takeyama** [comment]
> it's better to give feedbacks for official client

Alright, I think so too.

Actually, Slack Windows Ver. 0.9.5 released yesterday is really nice.
And right-click is handled correctly on that. (Ugly-font issues' also resolved!)

I close this issue.
